AWSTemplateFormatVersion: 2010-09-09
Description: Streamripper
Parameters: {}
Resources:
  StreamripperPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'sqs:*'
            Effect: Allow
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
        Version: 2012-10-17
      PolicyName: StreamripperPolicyName
      Roles:
        - !Ref StreamripperRole
  StreamripperRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
        Version: 2012-10-17
  StreamripperQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: StreamripperQueue
  StreamripperPBSTESTRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS Test Rule
      Name: Streamripper-PBS-Test-Rule
      ScheduleExpression: rate(1 minute)
      State: DISABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_Test_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "Test", "radiostation": "PBS", "duration": "5" }'
  StreamripperPBSSoulTimeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS SoulTime 11am Friday
      Name: Streamripper-PBS-SoulTime-Rule
      ScheduleExpression: cron(0 4 ? * WED *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_SoulTime_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "SoulTime", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSRiddimYardRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS RiddimYard 11am Friday
      Name: Streamripper-PBS-RiddimYard-Rule
      ScheduleExpression: cron(0 0 ? * FRI *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_RiddimYard_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "RiddimYard", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSRiddimYardRuleTemp:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS RiddimYard 11am Friday
      Name: Streamripper-PBS-RiddimYard-Rule-Temp
      ScheduleExpression: cron(50 0 ? * FRI *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_RiddimYard_RuleTemp1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "RiddimYard", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSBablyonBurningRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS BablyonBurning 5pm Saturday
      Name: Streamripper-PBS-BablyonBurning-Rule
      ScheduleExpression: cron(0 6 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_BablyonBurning_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "BablyonBurning", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSBossActionRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS BossAction 7pm Saturday
      Name: Streamripper-PBS-BossAction-Rule
      ScheduleExpression: cron(0 8 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_BossAction_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "BossAction", "radiostation": "PBS", "duration": "3600" }'
  StreamripperPBSFreshProduceRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS FreshProduce 7pm Saturday
      Name: Streamripper-PBS-FreshProduce-Rule
      ScheduleExpression: cron(0 9 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_FreshProduce_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "FreshProduce", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSPassingNotesRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS PassingNotes 9pm Friday
      Name: Streamripper-PBS-PassingNotes-Rule
      ScheduleExpression: cron(3 10 ? * FRI *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_PassingNotes_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "PassingNotes", "radiostation": "PBS", "duration": "7200" }'
  StreamripperQueuePolicy:
    DependsOn:
      - StreamripperQueue
      - StreamripperPBSTESTRule
      - StreamripperPBSRiddimYardRule
      - StreamripperPBSRiddimYardRuleTemp
      - StreamripperPBSBablyonBurningRule
      - StreamripperPBSBossActionRule
      - StreamripperPBSFreshProduceRule
      - StreamripperPBSPassingNotesRule
      - StreamripperPBSSoulTimeRule
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: StreamripperQueuePolicy
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
            Action: 'sqs:SendMessage'
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
      Queues:
        - !Ref StreamripperQueue
Outputs: {}
