AWSTemplateFormatVersion: 2010-09-09
Description: Streamripper
Parameters: {}
Resources:
  StreamripperPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'sqs:*'
            Effect: Allow
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
        Version: 2012-10-17
      PolicyName: StreamripperPolicyName
      Roles:
        - !Ref StreamripperRole
  StreamripperRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
        Version: 2012-10-17
  StreamripperQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: StreamripperQueue
  StreamripperPBSTESTRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS Test Rule
      Name: Streamripper-PBS-Test-Rule
      ScheduleExpression: rate(1 minute)
      State: DISABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_Test_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "Test", "radiostation": "PBS", "duration": "5" }'
  StreamripperPBSSoulTimeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS SoulTime 
      Name: Streamripper-PBS-SoulTime-Rule
      ScheduleExpression: cron(0 5 ? * WED *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_SoulTime_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "SoulTime", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSRiddimYardRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS RiddimYard 11am Friday
      Name: Streamripper-PBS-RiddimYard-Rule
      ScheduleExpression: cron(0 1 ? * FRI *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_RiddimYard_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "RiddimYard", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSBablyonBurningRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS BablyonBurning 5pm Saturday
      Name: Streamripper-PBS-BablyonBurning-Rule
      ScheduleExpression: cron(0 7 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_BablyonBurning_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "BablyonBurning", "radiostation": "PBS", "duration": "7200" }'
  StreamripperPBSBossActionRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS BossAction 7pm Saturday
      Name: Streamripper-PBS-BossAction-Rule
      ScheduleExpression: cron(0 9 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_BossAction_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "BossAction", "radiostation": "PBS", "duration": "3600" }'
  StreamripperPBSFreshProduceRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS FreshProduce 7pm Saturday
      Name: Streamripper-PBS-FreshProduce-Rule
      ScheduleExpression: cron(0 10 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_FreshProduce_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "FreshProduce", "radiostation": "PBS", "duration": "7200" }'
  StreamripperRRRGetDownRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: RRR GetDown 12pm Thursday
      Name: Streamripper-RRR-GetDown-Rule
      ScheduleExpression: cron(0 2 ? * THU *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper-RRR-GetDown-Rule1
          Input: '{ "url" : "http://public-radio1.internode.on.net:8002/114", "showname": "GetDown", "radiostation": "RRR", "duration": "7200" }'
  StreamripperCKUTWeFunkRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: WeFunk 12am Saturday EST (Montreal)
      Name: Streamripper-CKUT-WeFunk-Rule
      ScheduleExpression: cron(0 4 ? * SAT *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper-CKUT-WeFunk-Rule1
          Input: '{ "url" : "http://stream.ckut.ca:8000/903fm-192-stereo", "showname": "WeFunk", "radiostation": "CKUT", "duration": "7200" }'
  StreamripperBBC1XtraDavidRodiganRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: BBC1Xtra DavidRodigan Sunday 7pm UTC
      Name: Streamripper-BBC1Xtra-DavidRodigan-Rule
      ScheduleExpression: cron(0 12 ? * SUN *)
      State: ENABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper-BBC1Xtra-DavidRodigan-Rule1
          Input: '{ "url" : "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1xtra_mf_p", "showname": "DavidRodigan", "radiostation": "BBC1Xtra", "duration": "7200" }'
  StreamripperQueuePolicy:
    DependsOn:
      - StreamripperQueue
      - StreamripperPBSTESTRule
      - StreamripperPBSRiddimYardRule
      - StreamripperPBSBablyonBurningRule
      - StreamripperPBSBossActionRule
      - StreamripperPBSFreshProduceRule
      - StreamripperPBSSoulTimeRule
      - StreamripperRRRGetDownRule
      - StreamripperCKUTWeFunkRule
      - StreamripperBBC1XtraDavidRodiganRule
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: StreamripperQueuePolicy
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
            Action: 'sqs:SendMessage'
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
      Queues:
        - !Ref StreamripperQueue
Outputs: {}
