AWSTemplateFormatVersion: 2010-09-09
Description: Streamripper
Parameters: {}
Resources:
  StreamripperPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'sqs:*'
            Effect: Allow
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
        Version: 2012-10-17
      PolicyName: StreamripperPolicyName
      Roles:
        - !Ref StreamripperRole
  StreamripperRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
        Version: 2012-10-17
  StreamripperQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: StreamripperQueue
  StreamripperPBSTESTRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: PBS Test Rule
      Name: Streamripper-PBS-Test-Rule
      ScheduleExpression: rate(1 minute)
      State: DISABLED
      RoleArn: !GetAtt 
        - StreamripperRole
        - Arn
      Targets:
        - Arn: !GetAtt 
            - StreamripperQueue
            - Arn
          Id: Streamripper_PBS_Test_Rule1
          Input: '{ "url" : "http://eno.emit.com:8000/pbsfm_live_64.mp3", "showname": "Test", "radiostation": "PBS", "duration": "5" }'
  StreamripperQueuePolicy:
    DependsOn:
      - StreamripperQueue
      - StreamripperPBSTESTRule
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: StreamripperQueuePolicy
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
            Action: 'sqs:SendMessage'
            Resource: !GetAtt 
              - StreamripperQueue
              - Arn
      Queues:
        - !Ref StreamripperQueue
Outputs: {}
